/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package betaplication;

import javax.swing.JOptionPane;
import model.Aposta;
import model.Bilhete;
import model.Campeonato;
import model.Jogo;
import model.Premiacao;
import model.Rodada;
import model.Time;

/**
 *
 * @author antonio
 */
public class TelaInicio extends javax.swing.JFrame {
    
    private Rodada rodada;
    private Premiacao premiacao;
    private Bilhete bilhete;

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        Campeonato camp = new Campeonato("Campeonato Brasileiro", "BRA", "Brasil");
        camp.addTime(new Time("Flamengo", "FLA"));
        camp.addTime(new Time("Fluminense", "FLU"));
        camp.addTime(new Time("Vasco", "VAS"));
        camp.gerarJogos();
        Campeonato camp2 = new Campeonato("Campeonato Piauiense", "PI", "Piaui");
        camp2.addTime(new Time("River", "RIV"));
        camp2.addTime(new Time("Barras", "BAR"));
        camp2.gerarJogos();
        rodada = new Rodada();
        rodada.campeonatos.add(camp);
        rodada.campeonatos.add(camp2);
        premiacao = new Premiacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovoBilhete = new javax.swing.JButton();
        btnApostar = new javax.swing.JButton();
        btnVerApostas = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNovoBilhete.setText("Novo Bilhete");
        btnNovoBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoBilheteActionPerformed(evt);
            }
        });

        btnApostar.setText("Fazer Aposta");
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });

        btnVerApostas.setText("Ver Apostas");
        btnVerApostas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerApostasActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar Rodada / Verificar Boletos");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerApostas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnApostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovoBilhete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoBilhete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApostar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerApostas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoBilheteActionPerformed
        // TODO add your handling code here:
        if(bilhete != null && !bilhete.isPreenchido()){
            JOptionPane.showMessageDialog(null, "Já existe um bilhete nâo preenchido");
            return;
        }
        String nome = JOptionPane.showInputDialog("Nome do bilhete:");
        if (nome != null && !nome.isEmpty()) {
            bilhete = new Bilhete(nome);
            premiacao.addBilhete(bilhete);
        }
        
    }//GEN-LAST:event_btnNovoBilheteActionPerformed

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
        // TODO add your handling code here:
        if (bilhete != null) {
            if (!bilhete.isPreenchido()) {
                String texto = "Selecione o campeonato desejado: \n\n";
                for (int i = 0; i < rodada.campeonatos.size(); i++) {
                    texto += String.format("%d) %s \n", i+1,rodada.campeonatos.get(i).getNome());
                }
                Campeonato campeonato = rodada.campeonatos.get(
                        Integer.valueOf(JOptionPane.showInputDialog(texto))-1);
                texto = "Selecione um jogo: \n\n";
                for (int i = 0; i < campeonato.jogos.size(); i++) {
                    texto += String.format("%d) %s \n", i+1,campeonato.jogos.get(i).toString());
                }
                Jogo jogo = campeonato.jogos.get(
                        Integer.valueOf(JOptionPane.showInputDialog(texto))-1);
                for (Aposta a : bilhete.apostas) {
                    if (a.getJogo().equals(jogo)) {
                        JOptionPane.showMessageDialog(null, "Você já apostou nesse jogo");
                        return;
                    }
                }
                
                texto = JOptionPane.showInputDialog("Escolha o resultado: \n"
                        + "0) Empate \n" + "1) Time da casa ganha\n" + "2) Time da fora ganha");
                Aposta aposta = new Aposta(jogo, Integer.valueOf(texto) == 2?
                        -1:Integer.valueOf(texto));
                bilhete.apostas.add(aposta);
                if (bilhete.apostas.size() > 4) {
                    bilhete.setPreenchido(true);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Bilhete já preenchido");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Bilhete não criado");
        }
    }//GEN-LAST:event_btnApostarActionPerformed

    private void btnVerApostasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerApostasActionPerformed
        // TODO add your handling code here:
        if (bilhete != null) {
            String texto = "Apostas realizadas: \n\n";
            for (Aposta a: bilhete.apostas) {
                texto += a.toString() + "\n";
            }
            JOptionPane.showMessageDialog(null, texto);
        } else {
            JOptionPane.showMessageDialog(null, "Bilhete não criado");
        }
    }//GEN-LAST:event_btnVerApostasActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        rodada.finalizarRodada();
        premiacao.calcularVencendor();
        String texto = "Vencedores: \n\n";
        for (String s : premiacao.retornarVencendores()) {
            texto += s + "\n";
        }
        JOptionPane.showMessageDialog(null, texto);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnNovoBilhete;
    private javax.swing.JButton btnVerApostas;
    // End of variables declaration//GEN-END:variables
}
